version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./downloads:/usr/src/app/downloads
    environment:
      - NODE_ENV=production
